M48
; DRILL file KiCad 10.0.4 date 2026-09-01T20:45:53
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-01T20:45:53+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X143.1Y-40.36
T1
G00X136.05Y-40.36
M15
G01X135.75Y-40.36
M16
G05
M30
